ref(ui): Handle log output w/ react state
getsentry/freight pull request #370
Opened 2022-08-10 23:38 UTC by evanpurkhiser

2022-08-10 23:39 UTC, evanpurkhiser commented on static/views/TaskDetails.jsx
> +      );
So much better lol

2022-08-10 23:55 UTC, dcramer commented
Did you test the performance on this?

2022-08-10 23:57 UTC, dcramer commented
Like 99% this will not work and crushes UI rendering perf on build pages. This is done the way to optimize render times, which are horrifically slow in things like React.

2022-08-11 00:17 UTC, scttcper approved these changes
the key should keep it from rerendering

2022-08-11 00:21 UTC, dcramer requested changes
this is a production system. "should" is not good enough here. run the performance test locally if you're going to rewrite code.

2022-08-11 00:23 UTC, evanpurkhiser commented
> Did you test the performance on this?

Yeah I have a test script locally that outputs ~3k lines from our usual build logs with ~0.1s sleep between each line output.

Performance is totally fine, like @scttcper said, the `key` prop helps react know to not re-render everything

2022-08-11 00:23 UTC, dcramer commented
How long is the initial render with 3k lines of log? How long with 30k?

2022-08-11 00:23 UTC, evanpurkhiser commented
Let me check

2022-08-11 00:29 UTC, evanpurkhiser commented
Initial render w/ 3k lines looks like this
<img width="1063" alt="image" src="https://user-images.githubusercontent.com/1421724/184045155-4e469a1e-a1a7-41ea-9d73-03fde134a30a.png">

Initial render w/ the previous code w/ 3k lines looks like this

<img width="1422" alt="image" src="https://user-images.githubusercontent.com/1421724/184045310-57b15f23-ccc2-4b27-a1d7-5614092b02ab.png">

Looks like rendering w/ react is actually a bit faster.

That's all in debug mode too, I can generate a production build and look at that too, which i'm sure will be way faster.

2022-08-11 00:30 UTC, dcramer approved these changes

2022-08-11 00:46 UTC, evanpurkhiser commented on static/views/TaskDetails.jsx
> +const LogLineItem = React.memo(({index, item, highlighted, setHighlightedLine}) => {
Put this into a memoized component for a bit of extra optimization, so that the Ansi component doesn't try and re-render the line.

2022-08-11 00:47 UTC, scttcper approved these changes

2022-08-11 18:37 UTC, merged